Replace ResourceC's Handler type with that from MonadUnliftIO.
Since we use the `MonadUnliftIO` interface, we might as well get rid
of the `Handler` data type that clones the `UnliftIO` data type
provided by `MonadUnliftIO.`

Unfortunately, we can't use this to write a `MonadUnliftIO` instance
for `ReaderC (UnliftIO m) m` and then use `-XGeneralizedNewtypeDeriving`
to derive `MonadUnliftIO` instances for all effects that need it, as
we run into a role-related representation issue:

```
src/Control/Effect/Resource.hs:98:96: error:
    • Couldn't match representation of type ‘m (UnliftIO
                                                  (ResourceC m))’
                               with that of ‘m (UnliftIO (UnliftC m))’
        arising from the coercion of the method ‘askUnliftIO’
          from type ‘UnliftC m (UnliftIO (UnliftC m))’
            to type ‘ResourceC m (UnliftIO (ResourceC m))’
      NB: We cannot know what roles the parameters to ‘m’ have;
        we must assume that the role is nominal
    • When deriving the instance for (MonadUnliftIO (ResourceC m))
```

Doing so would require exposing an unsafe function, though, which
isn't great, so it's not an unmitigated tragedy.